apiVersion: apps/v1
kind: Deployment
metadata:
  name: bikemgmt
  labels:
    app: bikemgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bikemgmt
  template:
    metadata:
      labels:
        app: bikemgmt
    spec:
      containers:
        - name: bikemgmt
          image: agellid/bikemgmt:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
